name: Deploy Customer Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instalar Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Compilar TypeScript
      - name: Build TypeScript
        run: npm run build

      # 5️⃣ Crear ZIP listo para Lambda
      - name: Create ZIP artifact
        run: zip -r customer.zip dist node_modules package.json

      # 6️⃣ Subir a S3
      - name: Upload ZIP to S3
        run: aws s3 cp customer.zip s3://newbank-lambda-artifacts-dev/customer.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      # 7️⃣ (Opcional) Validar contenido
      - name: List S3 bucket content
        run: aws s3 ls s3://newbank-lambda-artifacts-dev/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
