name: Deploy Customer Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Compilar TypeScript
      - name: Build TypeScript
        run: npm run build

      # 5. Revisar archivos y generar ZIP
      - name: List workspace files
        run: ls -la $GITHUB_WORKSPACE

      - name: Create ZIP artifact
        run: |
          echo "Working dir: $(pwd)"
          zip -r $GITHUB_WORKSPACE/customer.zip dist node_modules package.json

      # 6. Subir el ZIP a S3
      - name: Upload artifact to S3
        run: aws s3 cp $GITHUB_WORKSPACE/customer.zip s3://newbank-lambda-artifacts-dev/customer.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
